name: Build Accounts-Manager Native Image

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build-native-image:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Updated to use Node.js 20

      - name: Download and Extract GraalVM
        run: |
          wget https://download.oracle.com/graalvm/21/latest/graalvm-jdk-21_linux-x64_bin.tar.gz
          tar -xzf graalvm-jdk-21_linux-x64_bin.tar.gz
          ls -l
          sudo mv graalvm-jdk-21* /usr/lib/jvm/graalvm

      - name: Set up GraalVM
        run: |
          echo "JAVA_HOME=/usr/lib/jvm/graalvm" >> $GITHUB_ENV
          echo "PATH=/usr/lib/jvm/graalvm/bin:$PATH" >> $GITHUB_ENV
          source $GITHUB_ENV

      - name: Verify GraalVM Installation
        run: |
          source $GITHUB_ENV
          java -version
          native-image --version

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '8.5-rc-2'

      - name: Build Native Image
        run: |
          source $GITHUB_ENV
          ./gradlew nativeCompile

      - name: Upload Native Image Artifact
        uses: actions/upload-artifact@v3
        with:
          name: accounts-manager-native
          path: build/native/nativeCompile/accounts-manager
