name: Build Accounts-Manager Native Image

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build-native-image:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download and Extract GraalVM
        run: |
          wget https://github.com/graalvm/graalvm-ce-builds/releases/download/jdk-22.0.1/graalvm-community-jdk-22.0.1_linux-x64_bin.tar.gz
          tar -xzf graalvm-community-jdk-22.0.1_linux-x64_bin.tar.gz

      - name: Set up GraalVM
        run: |
          sudo mkdir -p /usr/lib/jvm/graalvm/bin
          sudo cp graalvm-community-openjdk-22.0.1+8.1/bin/* /usr/lib/jvm/graalvm/bin/
          sudo cp -r graalvm-community-openjdk-22.0.1+8.1/lib /usr/lib/jvm/graalvm/
          sudo update-alternatives --install /usr/bin/java java /usr/lib/jvm/graalvm/bin/java 1
          sudo update-alternatives --set java /usr/lib/jvm/graalvm/bin/java
          export PATH=$PATH:/usr/lib/jvm/graalvm/bin
          export JAVA_HOME=/usr/lib/jvm/graalvm

      - name: Verify GraalVM Installation
        run: |
          java -version
          gu --version
          gu list

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '8.5-rc-2'

      - name: Build Native Image
        run: ./gradlew nativeCompile

      - name: Upload Native Image Artifact
        uses: actions/upload-artifact@v3
        with:
          name: accounts-manager-native
          path: build/native/nativeCompile/accounts-manager
