name: Build Accounts-Manager Native Image

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build-native-image:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          version: '21.0.1'
          java-version: '21'
          components: 'native-image'

      - name: Verify GraalVM Installation
        run: |
          java -version
          gu --version
          gu list

      - name: Install Native Image Component
        run: gu install native-image

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '8.5-rc-2'

      - name: Build Native Image
        run: ./gradlew nativeCompile

      - name: Upload Native Image Artifact
        uses: actions/upload-artifact@v3
        with:
          name: accounts-manager-native
          path: build/native/nativeCompile/accounts-manager
