name: Build Accounts-Manager Native Image

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build-native-image:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download and Extract GraalVM
        run: |
          wget https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-21.0.1/graalvm-ce-java21-linux-amd64-21.0.1.tar.gz
          tar -xzf graalvm-ce-java21-linux-amd64-21.0.1.tar.gz
          sudo mv graalvm-ce-java21-21.0.1 /usr/lib/jvm/graalvm

      - name: Set up GraalVM
        run: |
          echo "JAVA_HOME=/usr/lib/jvm/graalvm" >> $GITHUB_ENV
          echo "PATH=/usr/lib/jvm/graalvm/bin:$PATH" >> $GITHUB_ENV
          source $GITHUB_ENV

      - name: Verify GraalVM Installation
        run: |
          source $GITHUB_ENV
          java -version
          native-image --version

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '8.5-rc-2'

      - name: Build Native Image
        run: |
          source $GITHUB_ENV
          ./gradlew nativeCompile

      - name: Upload Native Image Artifact
        uses: actions/upload-artifact@v3
        with:
          name: accounts-manager-native
          path: build/native/nativeCompile/accounts-manager

